### PR TITLE
Adding Keywords Functionality To Publisher

### PR DESCRIPTION
**Pull request by simonv3**
Here's the PR from my own branch. Made some fixes so that TravisCI passes.

### CODE REVIEW

**Comment by Floppy** [comment]
Superb, I'll give it a quick test here and merge.

**Comment by Floppy** [comment]
Mm, my keyword permissions are a bit broken here, but generally it looks fine, so I'll merge and get the guys to check on live.

**Comment by Floppy** [comment]
Only thing I'm not sure about is if it needs a separate publisher keywords permission adding to signon - did you need to do that, or does it work with the existing one from panopticon?

**Comment by simonv3** [comment]
I had a couple of issues to do with permissions (because the default users don't get given them, I had to prod through the code to figure out how they worked).

Looking at db.publisher_users.find() it does look like I gave my test user permission to `keywords` (["signin", "keywords"]), but I'm not sure if that's actually having an effect. I would assume that it accesses the publisher user permissions.

**Comment by simonv3** [comment]
Made that PR here: https://github.com/theodi/signonotron2/pull/38

**Comment by Floppy** [comment]
OK, good to go.

**Comment by Floppy** [comment]
@langphil you will need to add "keywords" permissions for people who have it in panopticon to publisher as well. Can you handle that?

**Pull request merged**
