### PR TITLE
In Progress: Add Keyword Management To Publisher

### PR DESCRIPTION
**Pull request by simonv3**
Based off of keyword management in Panopticon, this adds keyword management to the publisher edition screen, if the user has keyword adding permissions.

To do:
* [ ] pass tests locally (though I don't know if they're failing because of these additions or they're just failing. Travis will tell.
* [ ] add tests for this feature.

### CODE REVIEW

**Comment by Floppy** [comment]
@simonv3 I've pulled this into a simonv3-master branch on this repo, so we can run the tests. I've also invited you to the collaborators so you can work directly here, avoiding the test problems.

**Comment by Floppy** [comment]
OK, @simonv3, 5 fails by the look of it: https://travis-ci.org/theodi/publisher/builds/56717245

**Comment by Floppy** [comment]
All look like they're `invalid query` when storing tags, so I guess that's related to this work.

**Comment by Floppy** [comment]
Might be worth closing this PR, working in the local simonv3-master branch, and opening a new one.

**Comment by simonv3** [comment]
Thanks @Floppy, I'll go test on that branch.

**Pull request closed without merging**
